### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Automatic logut plugin makes etherpad crash when trying to uninstall it. This plugin hasn't been upgraded since 5 years.

### CODE REVIEW

**Comment by ericgaspar** [comment]
)testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — APPROVED** [review]
After a look into the code and testing at home, LGTM!
(Hopefully the CI will agree 😛)

**Review by yalh76 — APPROVED** [review]
LGTM

**Pull request merged**
