### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *It's not possible to include a pad in a frame. The Libreto package need it.*
- *Packaging rules have changed*

## Solution
- *Change the header*
- *Update to last packaging standard*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : [Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/etherpad_mypads_ynh%20PR63/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Suggesting to merge at least #62 before advertising that testing release.

**Comment by maniackcrudelis** [comment]
Ready to be reviewed.
The CI was failing, but I tested it on my own and it worked.
I expect the next test to be ok
[Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/etherpad_mypads_ynh%20PR63/)

**Comment by JimboJoe** [comment]
Well I can't technically review this PR (which I opened), but LGTM and code review for me :+1:

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days.

**Pull request merged**
