### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Permissions are not set back during the restoration, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/52#issuecomment-423254171*
- Mypads needs to be updated *https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/51#issuecomment-426984493*

## Solution
- *Set the permissions in the restore script.*
- *Update Mypads plugin*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Anmol
- [x] **Approval (LGTM)** : Anmol
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/etherpad_mypads_ynh%20testing%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
The upgrade test fails because of an error with the new version of mypads, it should be soon fixed.

**Comment by maniackcrudelis** [comment]
Ready to be reviewed

**Comment by frju365** [comment]
Will be merged in 3 day if nobody is against.

**Comment by maniackcrudelis** [comment]
Can now be reviewed.

@Anmol, please take note that there's a new commit since your last approval and code review.

**Comment by maniackcrudelis** [comment]
Looks like this PR can be merged...
I'll merge it in 3 days then.

**Pull request merged**
