### PR TITLE
time remaining

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *--time*

## Solution
- *remove it*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/etherpad_mypads_ynh%20PR70/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
https://github.com/YunoHost-Apps/etherpad_mypads_ynh/commit/8bf300413ec3adcb416d168d2e9e98975dd9405b

This is a quite old commit, couldn't we not test it?

**Comment by maniackcrudelis** [comment]
Huh, what about the double negation ? What did you mean ?

**Comment by maniackcrudelis** [comment]
Going through all that PR, I get that the problem is about the test `Upgrade from  Fix nodejs & global update` which has failed.
I notice that it has failed as well on https://ci-apps.yunohost.org/ci/job/4278
That's indeed an old commit, but that's the purpose of this test.
It shouldn't affect the result of this PR though, which is obviously not related to that test.

Still, before getting rid of this commit, we should be sure that we're not carrying a bug from the upgrade script.
My hint is, though, that the install from this version doesn't work at all anymore. Should be tested though of course.

**Comment by kay0u** [comment]
The last tests was on 3.5.2, my guess is that the 3.6 break the old version of this app, but I'm not sure, and don't know how...

**Comment by kay0u** [comment]
LGTM please?

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
