### PR TITLE
Upgrade to 1.8.13

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 1.8.13

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — DISMISSED** [review]
LGTM

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — DISMISSED** [review]

**Review by yalh76 — DISMISSED** [review]

**Pull request merged**
