### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Remove page_view plugin (part of the core now)
- Set new permissions

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — DISMISSED** [review]
LGTM

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
