### PR TITLE
Upgrade to 1.7.0

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Etherpad fails to start because of a syntax error (see https://forum.yunohost.org/t/etherpad-mypads-502-bad-gateway-migration-yunohost-2-7-3-1/5468/2)*
- *The update of the npm modules is not fully functional.*
- *Etherpad and mypads are not up to date.*
- Fix https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/36, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/39, https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/47 and PR https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/45

## Solution
- *Upgrade Etherpad to 1.7.0*
- *Upgrade Mypads module to 1.6.2*
- *Fix the way modules are updated*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/etherpad_mypads_ynh%20update17%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
No impact [here](https://github.com/YunoHost-Apps/etherpad_mypads_ynh/blob/master/conf/app.src#L1)...? :thinking:

**Comment by maniackcrudelis** [comment]
My bad, I commited on my VM...

**Comment by maniackcrudelis** [comment]
Now that the CI tests are good, let's merge in 3 days.

**Comment by ldidry** [comment]
Please use MyPads 1.6.8 ASAP, a bug can prevent access to some folders.

**Comment by ldidry** [comment]
A new version has been released! You can now have a job queue to delete the pads instead of letting Etherpad doing it. The ORM of Etherpad, ueberdb2, completely freezed Etherpad while deleting huge pads, due to its cache and the mono-processus behavior of NodeJS.
On my dev instance, it froze Etherpad for ±20 minutes for deleting a pad with 72,000 revisions. The job queue not only avoids the freeze but also avoids timeout for the request that asked for deletion and the deletion itself only took less than a second.

The use of the job queue asks to install a new .service on systemd (see the [wiki](https://framagit.org/framasoft/Etherpad/ep_mypads/wikis/use-the-job-queue)).

The use of the job queue is deactivated per default and must be enabled in the admin interface (or by setting the `mypads:conf:deleteJobQueue` DB record to `true`).

The use of the job queue is recommended.

https://framagit.org/framasoft/Etherpad/ep_mypads/tags

**Pull request merged**
